appName: graphql-server

namespace: default

databaseUrl: "mysql://rbs_staging:Jodk7MELXFCet_AgfE7mVy.Dqpofr6go@testdatabase.clex5umouqji.us-east-1.rds.amazonaws.com:3306/responsitest_dev_app"

image:
  repository: "914958427285.dkr.ecr.us-east-1.amazonaws.com/responsibid-server"
  tag: develop-latest
  pullSecret:
    name: responsibid-staging

port: "3333"