apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.appName }}
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      name: {{ .Release.Name }}-pod
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        name: {{ .Release.Name }}-pod
        tier: backend
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
